= GitHub Actions
:author: hituzi no sippo
:email: dev@hituzi-no-sippo.me
:revnumber: v0.5.0
:revdate: 2023-11-05T20:05:57+09:00
:revremark: add design rule that a single job runs only one task
:copyright: Copyright (C) 2023 {author}

== Setup

=== Repository setting on GitHub

// tag::repository_setting_on_github[]

==== Install GitHub App and create secrets to create commit

:workflow_directory_path: ../../../.github/workflows
.Workflows used GitHub App
* xref:{workflow_directory_path}/.github/workflows/update_aqua_checksum.yml[
  Update aqua checksum]

Required to create commit on GitHub Actions.

. Create GitHub App
+
.GitHub App permission
[CAUTION]
====
Need to GitHub app has `Read and Write` access to
content of repository permission.
====
. Install the GitHub App into a repository
. Create the following two secrets encrypted secrets for the GitHub App
** `APP_ID`
** `PRIVATE_KEY`

:github_docs_url: https://docs.github.com/en
.References
* link:{github_docs_url}/actions/security-guides/encrypted-secrets?tool=webui#creating-encrypted-secrets-for-an-environment[
  Creating encrypted secrets for an environment - Encrypted secrets^]
* link:{github_docs_url}/apps/creating-github-apps/registering-a-github-app/choosing-permissions-for-a-github-app#choosing-permissions-for-rest-api-access[
  Choosing permissions for REST API access - Choosing permissions for a GitHub App^]
* link:{github_docs_url}/apps/creating-github-apps/authenticating-with-a-github-app/managing-private-keys-for-github-apps#generating-private-keys[
  Generating private keys - Managing private keys for GitHub Apps^]
* link:{github_docs_url}/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents[
  Repository permissions for "Contents" - Permissions required for GitHub Apps^]

// end::repository_setting_on_github[]

== Design

=== Job

==== A single job runs only one task

When multiple tasks into a single job (runner),
it becomes difficult to understand which step depends on which a task.

pass:[<!-- vale RedHat.Contractions = NO -->]
// I do not know the word that can replace 'It's fine'.

It's fine to change the number of tasks ran in a single job
from one to multiple.
The rule of runs only one task in a single job
does not necessarily have to be followed.

pass:[<!-- vale RedHat.Contractions = error -->]

Separating multiple tasks by job takes more resources such as time than
if run multiple tasks into a single job.
For each job, the following process are performed, so it takes resources

.Process per job
* Provisions a new VM to runs the job
* Clone the repository

.References
* link:{github_docs_url}/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#using-a-github-hosted-runner[
  Using a GitHub-hosted runner - About GitHub-hosted runners^]

.A single job runs only one task
[source, YAML]
----
jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4.1.1

      - name: format
        run: ...

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4.1.1

      - name: lint
        run: ...
----

.A single job run multiple tasks
[source, YAML]
----
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4.1.1

      - name: format
        run: ...

      - name: lint
        run: ...
----

'''

The license for this document is link:https://choosealicense.com/licenses/mit-0/[
MIT-0^] License. +
Does not require preservation of copyright and license notices.

:author_link: link:https://github.com/hituzi-no-sippo[{author}^]
Copyright (C) 2023 {author_link}
