---
name: Install tools with aqua
description: Install tools with aqua

runs:
  using: composite
  # References
  # https://aquaproj.github.io/docs/products/aqua-installer#-caching
  steps:
    # This action does not automatically create a new cache if the job fails.
    # Job Results and Automatic Cache Creation
    # Successfully: Automatically create a cache
    # Failed:       Does not create cache
    # https://github.com/actions/cache/tree/v3.3.1#using-a-combination-of-restore-and-save-actions
    - name: Cache aqua
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.local/share/aquaproj-aqua
        key: ${{ env.CACHE_PREFIX }}${{hashFiles('.aqua/**/*.yml')}}
        restore-keys: ${{ env.CACHE_PREFIX }}
      env:
        CACHE_PREFIX: v1-aqua-installer-${{ runner.os }}-${{ runner.arch }}-

    - name: Install tools with aqua
      # yamllint disable-line rule:line-length
      uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
      with:
        aqua_version: v2.22.0
        # Does not use `-l` or `--only-link` flags to cache all tools.
        aqua_opts: ""
      env:
        AQUA_LOG_LEVEL: debug
        AQUA_LOG_COLOR: always
