---
name: Install Ruby gems
description: Install Ruby gems with bundler

runs:
  using: composite
  steps:
    - name: Install Ruby and gems with bundler
      uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4 # v1.207.0
      with:
        # https://github.com/ruby/setup-ruby/blob/a05e47355e80e57b9a67566a813648fa67d92011/action.yml#L8-L9
        # v1.157.0 Commit on 2023-10-21
        # Decide the version for Ruby from `.ruby-version` file.
        ruby-version: .ruby-version
        # https://github.com/ruby/setup-ruby/blob/a05e47355e80e57b9a67566a813648fa67d92011/action.yml#L17-L21
        # v1.157.0 Commit on 2023-10-21
        # - Gemfile.lock
        #   the version of the BUNDLED WITH section
        #   from the Gemfile.lock if it exists.
        #   If the file or section does not exist then the same as 'default'.
        # - default
        #   if the Ruby ships with Bundler 2.2+ as a default gem,
        #   that version is used, otherwise the same as 'latest'.
        bundler: Gemfile.lock
        bundler-cache: true
