= Configuration
:author: hituzi no sippo
:email: dev@hituzi-no-sippo.me
:revnumber: v0.9.0
:revdate: 2023-10-21T07:57:00+09:00
:revremark: add description of `automergeSchedule`
:copyright: Copyright (C) 2023 {author}

// tag::body[]

:renovate_doc_url: https://docs.renovatebot.com
:config_options_url: {renovate_doc_url}/configuration-options

// tag::main[]

:display_file_path: ../../../_partials/display_file_in_details_disclosure_element.adoc
:block_title_name: Configuration file
:file_path_from_root: .renovaterc.json
:file_lang: JSON
include::{display_file_path}[]

.Automerge
[horizontal]
Major(`1.0.0` => `2.0.0`):: disable
Minor(`1.0.0` => `1.1.0`):: disable
Patch(`1.0.0` => `1.0.1`):: Enable

.Day required before a new release is considered stable (`minimumReleaseAge`)
[horizontal]
Major(`1.0.0` => `2.0.0`):: 2 weeks
Minor(`1.0.0` => `1.1.0`):: 1 week
Patch(`1.0.0` => `1.0.1`):: 3 days

.`automerge` and `minimumReleaseAge` change the timing of PR creation
[NOTE]
====
.`automerge`
false::
  Renovate does not create a PR immediately. +
  Renovate creates a PR,
  when the time specified by `minimumReleaseAge` has passed
  after the version is released.
true::
  Renovate create a PR immediately, but does not automerge immediately. +
  Renovate merges a PR,
  when the time specified by `minimumReleaseAge` has passed
  after the version is released.

.References
* link:{config_options_url}/#suppress-branchpr-creation-for-x-days[
  Suppress branch/PR creation for X days - Configuration Options^]
* link:{config_options_url}/#await-x-time-duration-before-automerging[
  Await X time duration before Automerging - Configuration Options^]
====

.Schedule
[horizontal]
Create a branch (`schedule`)::
  link:{config_options_url}/#schedule[
  `at any time`^]
Automerge (`automergeschedule`)::
  link:{config_options_url}/#automergeschedule[
  `at any time`^]

.If you feel that Renovate is too noisy
[NOTE]
====
.Change the values of the following options
* schedule
** `schedule`
** `automergeschedule`
* Limit
** `prConcurrentLimit`
** `branchConcurrentLimit`

See link:{renovate_doc_url}/noise-reduction/[Noisy Reduction^]
====

// end::main[]

// end::body[]

'''

The license for this document is link:https://choosealicense.com/licenses/mit-0/[
MIT-0^] License. +
Does not require preservation of copyright and license notices.

:author_link: link:https://github.com/hituzi-no-sippo[{author}^]
Copyright (C) 2023 {author_link}
