= Natural Language
:author: hituzi no sippo
:email: dev@hituzi-no-sippo.me
:revnumber: v0.6.0
:revdate: 2023-07-13T20:39:20+09:00
:revremark: add vocabularies
:copyright: Copyright (C) 2023 {author}

:github_url: https://github.com
:root_directory: ../../..
:base_directory: {root_directory}/.vale/styles/Vocab/Base

== Lint

:vale_url: https://vale.sh
Use link:{vale_url}[Vale^].

link:{root_directory}/.vale.ini[Configuration File^]

.Supported formats
* HTML
* Markdown
* AsciiDoc
* Org
* Source Code Comments
** C
** JavaScript
** Python
** Go
** CSS

:vale_topic_docs_url: {vale_url}/docs/topics
For more supported file types,
please read link:{vale_topic_docs_url}/scoping[Vale Scoping^].

=== Vocabularies

link:{vale_topic_docs_url}/vocab/[
Vale can define preferred and avoid vocabulary terms^].

We define terms into the following files:

.Term Files
[horizontal]
Preferred (`Vale.Terms`):: link:{base_directory}/accept.txt[accept.txt^]
Avoid (`Vale.Avoid`):: `{base_directory}/reject.txt`

== Spell check

=== Documentations

.Spelling
Vale can check spelling (`Vale.Spelling`).
We can ignore words in link:{base_directory}/vocab.txt[vocab.txt^] with
link:{github_url}/errata-ai/vale/blob/v2/internal/rule/Vale/Spelling.yml[
spell check^].

'''

This document is licensed under link:https://choosealicense.com/licenses/mit-0/[
MIT-0^] License. +
Preservation of copyright and license notices isn't required.

:author_link: link:https://github.com/hituzi-no-sippo[{author}^]
Copyright (C) 2023 {author_link}
