---
name: Lint Natural Language of docs

on:
  push:
    paths:
      # This glob is the targets of vale.
      # Vale sets the targets in `.vale.ini`.
      - README.*
      - docs/**
      # Runs this workflow when update version for Asciidoctor
      # because Vale uses Asciidoctor when Vale lint a AsciiDoc.
      - Gemfile.lock
      - .github/workflows/lint_natural_language_of_docs.yml
      - .github/actions/install_ruby_gems/action.yml
      - .github/actions/run_task_runner/action.yml
      - .lefthook/docs/lint_natural_language.yml

permissions: {}

defaults:
  run:
    # Add `-o pipefail` option to bash
    # References
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  lint_natural_language_of_docs:
    name: lint Natural Language of docs
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Create timeline of this GitHub Actions workflow
        # yamllint disable-line rule:line-length
        uses: Kesin11/actions-timeline@40b912d44677e158feec8015d092b5428f9c8247 # v2.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Runtime security for GitHub
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            index.rubygems.org:443
            objects.githubusercontent.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443
            raw.githubusercontent.com:443
            rubygems.org:443

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install tool version manager and task runner
        uses: ./.github/actions/install_tools_with_aqua

      - name: Download and install external rules for linter
        run: vale sync

      # Requires Asciidoctor to lint AsciiDoc on Vale.
      - name: Install Asciidoctor
        uses: ./.github/actions/install_ruby_gems

      - name: Lint
        run: |
          lefthook run lint \
            --commands=lint-natural-language-of-docs
